apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: payment-db
  labels:
    app: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: mauricio1998/payment-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017