apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: mauricio1998/payment-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3011
          volumeMounts:
            - name: payment-service
              subPath: config.yaml
              mountPath: /go/app/config.yaml
      volumes:
        - name: payment-service
          configMap:
            name: "payment-service"