apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 3011
      targetPort: 3011
      name: rest
  type: ClusterIP