apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-payment
  labels:
    app: tech-challenge-payment
spec:
  selector:
    app: tech-challenge-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: rest
  type: ClusterIP